### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by pkej** [duartealexf/sql-ddl-to-json-schema#35]
Thank you for fixing #19, I tested the parser now, and it works wonderfully! Now I'm going to test this with Feathers and see if I can create services from the output. As you can guess I've been on a hiatus on my project and just returned to it :)

**Comment by duartealexf** [comment]
Welcome back!
Good to know :) Let me know if there is anything else that is not working properly!

**Comment by pkej** [comment]
The rest (converting the json schema to a slightly more js-friendly format) I will do with some regexp in my code, and I'll see if I can create a batch-job from the parser to run with @feathers-plus/cli in order to automate my process further.
