### ISSUE TITLE
sql to an array of tables in a compact JSON format but lose "ON UPDATE"

### ISSUE THREAD

**Issue by HUxiaoAlinNG** [duartealexf/sql-ddl-to-json-schema#45]
DROP TABLE IF EXISTS `myscrm_organization`;
CREATE TABLE `myscrm_organization` (
  ===ignore===
  `ModifiedOn` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  ===ignore===
) 
I have a problem,the sql statement "`ModifiedOn` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',"through the function fead and toCompactJson parse and deliver will be 
"{
columns:
{  name: "ModifiedOn",
   options: {nullable: true, default: "CURRENT_TIMESTAMP", comment: "修改时间"},
type: {datatype: "datetime", fractional: 0},}"
and I will save the result to mongodb and I will parse the result to sql.
but,where is the mark that can know "ON UPDATE".
so I only can parse it to " `ModifiedOn` datetime DEFAULT 'CURRENT_TIMESTAMP' COMMENT '修改时间',",but I really want the result is " `ModifiedOn` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
"
so?how to parse it?

**Comment by duartealexf** [comment]
Hi @HUxiaoAlinNG ty I will take a look at it... i don't think the compact JSON has output of table triggers.

**Comment by duartealexf** [comment]
@HUxiaoAlinNG i just fixed this. Please update to 3.1.1 :)
You'll now see a " onUpdate" in the compact JSON.
