### ISSUE TITLE
Drop Table not working

### ISSUE THREAD

**Issue by diwakarRam** [duartealexf/sql-ddl-to-json-schema#46]
Drop Table query is not working for me.

node version: 8.10.0

My index.js file 

const Parser = require('sql-ddl-to-json-schema');
const parser = new Parser('mysql');
 
const sql = `CREATE TABLE Persons (
    PersonID int,
    LastName varchar(255),
    FirstName varchar(255),
    Address varchar(255),
    City varchar(255) 
);
 
Drop Table Persons;
`;
 
const options = {extension: '.json'};
 
parser.feed(sql)
  .toJsonSchemaFiles(__dirname, options)
  .then((outputFilePaths) => {
    console.log(outputFilePaths);
  });

package.json

{
  "name": "sql-ddl",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}

**Comment by duartealexf** [comment]
I have tested with the latest version and it is working fine.

The output is empty because you have dropped the table you have just created.

Remove the "Drop Table Persons" statement to see the output.
