### ISSUE TITLE
json-to-sql-ddl

### ISSUE THREAD

**Issue by tyfarnan** [duartealexf/sql-ddl-to-json-schema#58]
Hi, great project!

Wondering if you are aware of/working on the conversion in the other direction, ie converting this json-schema back into sql-ddl such that it can be processed by the database?

Thank you,
Tyler

**Comment by tyfarnan** [comment]
For example: https://github.com/mWater/jsonql

**Comment by duartealexf** [comment]
Hi @tyfarnan 
Thanks :)

I have received such a request before (#57 [comment](https://github.com/duartealexf/sql-ddl-to-json-schema/issues/57#issuecomment-612193119)). So perhaps I should create another library for doing that, something like json-schema-to-sql-ddl and link it to this project.

What is your use case?
Cheers

**Comment by duartealexf** [comment]
I'll be closing this since I have received no response.

**Comment by renaatdemuynck** [comment]
Hi is creating this json-schema-to-sql-ddl project still an option? I've been spending the better part of the day looking for something like that, but without success :-(

**Comment by duartealexf** [comment]
Hi @renaatdemuynck, yes it still is an option. But I just can't find the time to do it. Are you willing to create it? :D

**Comment by renaatdemuynck** [comment]
If I end up writing something myself, I will certainly share it :-)
