### ISSUE TITLE
sql parse failed

### ISSUE THREAD

**Issue by hp0912** [duartealexf/sql-ddl-to-json-schema#63]
There are more than 12 indexes,  sql parse failed

```sql
DROP TABLE IF EXISTS `b_regbroker`;
CREATE TABLE `b_regbroker`  (
  `CreatedOn` datetime(0) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`b_regbrokerId`) USING BTREE,
  INDEX `IX_cst_id`(`cst_id`) USING BTREE,
  INDEX `IX_ClueId`(`clueId`) USING BTREE,
  INDEX `IX_regbroker_id`(`regbroker_id`) USING BTREE,
  INDEX `IX_token`(`token`) USING BTREE,
  INDEX `IX_store_code`(`store_code`) USING BTREE,
  INDEX `IX_proj_id`(`proj_id`) USING BTREE,
  INDEX `IX_remind_date`(`remind_date`) USING BTREE,
  INDEX `IX_CreatedOn`(`CreatedOn`) USING BTREE,
  INDEX `IX_lose_clue_id`(`lose_clue_id`) USING BTREE,
  INDEX `IX_belongs_company`(`belongs_company`) USING BTREE,
  INDEX `IX_regbroker_id,CreatedOn`(`regbroker_id`, `CreatedOn`) USING BTREE,
  INDEX `IX_regbroker_id,check_date`(`regbroker_id`, `check_date`) USING BTREE,
  INDEX `IX_regbroker_id,last_report_time`(`regbroker_id`, `last_report_time`) USING BTREE,
  INDEX `IX_proj_id,CreatedOn`(`proj_id`, `CreatedOn`) USING BTREE,
  INDEX `IX_store_id,check_date`(`store_id`, `check_date`) USING BTREE
) ENGINE = InnoDB;

```

**Comment by duartealexf** [comment]
Hi @hp0912 

Thanks for raising this issue. This SQL parsing fails for me too. When the SQL statement is too long, the parsing time increases exponentially.

I'm sorry, this is just like issue #43 and unfortunately there's not a lot I can do to fix this specific parsing per se, but to change the parsing engine altogether (like, from Nearley to PEG.js or chevrotain). Doing so would take me months (but it's still on the roadmap, I'm not ignoring this). I just need the time to do so, btw contributions are always welcome.

The easiest way to fix this for now is to separate the INDEX lines into separate ALTER TABLE statements. Depending on which software created this SQL, there might be a flag you can use to do this automatically. It would look like, for example:

```sql
DROP TABLE IF EXISTS `b_regbroker`;

CREATE TABLE `b_regbroker`  (
  `CreatedOn` datetime(0) NULL DEFAULT NULL COMMENT ''
) ENGINE = InnoDB;

ALTER TABLE `b_regbroker` ADD PRIMARY KEY (`b_regbrokerId`) USING BTREE;
ALTER TABLE `b_regbroker` ADD INDEX `IX_cst_id`(`cst_id`) USING BTREE;
...
```

Again, I'm really sorry. I hope this does not block you from doing what you needed to do.
