### ISSUE TITLE
question: foreign keys, m/m relationships

### ISSUE THREAD

**Issue by flipkickmedia** [duartealexf/sql-ddl-to-json-schema#66]
Ive just done a conversion from a fairly standard set of SQL create table statements which has a pivot table and the relationships are defined as foreign keys.

1- Are there any other requirements to making JSON schemas work correctly with foreign keys other than simply having them defined in the SQL?
2- are m/m relationships supported?

If this functionality is missing or incomplete Id like to contribute!

**Comment by duartealexf** [comment]
Hi @flipkickmedia. I'm not sure what you mean by "functionality". Also, what do you mean by "JSON schemas work correctly with foreign keys"? Can you give me an use case?

Thanks.

**Comment by duartealexf** [comment]
I will be closing this for now as I have received no reply from my last question.
