### ISSUE TITLE
Number not suitable for expressing large decimals

### ISSUE THREAD

**Issue by GaryStrange** [duartealexf/sql-ddl-to-json-schema#72]
Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number

Number rounds at 17 decimal places.

When a numeric(32,6) is specified, the code will generate a string...

99999999999999999999999999.999999

When converted to a number becomes.

1e+26 which is larger than numeric(32,6)

https://github.com/duartealexf/sql-ddl-to-json-schema/blob/a3c342cae01d9d36538fb0f02eeed88a715e025b/src/mysql/formatter/json-schema/models/datatype.ts#L169

**Comment by duartealexf** [comment]
Hi @GaryStrange thanks for opening this issue.

Maybe you could help me with this one..? What is the largest value that can be stored in `numeric(32,6)`?

Thanks :)

**Comment by GaryStrange** [comment]
99999999999999999999999999.999999

**Comment by duartealexf** [comment]
> I dont' think there is any need to use a Number. Just create the string and store it as a string.

JSON Schema is all about validating data value and its format. Representing a number via a string sounds like it would break this. If the largest value that can be stored by numeric(32,6) is indeed 99999999999999999999999999.999999 then the code does not look broken.

Do you have a specific use case in which you need to convert to Number?

**Comment by duartealexf** [comment]
@GaryStrange I have received no reply from my previous question and will be closing this for now, as I can't tell if it's really a problem with this lib.
