### ISSUE TITLE
Support for SQLite `ON CONFLICT`

### ISSUE THREAD

**Issue by DukeManh** [duartealexf/sql-ddl-to-json-schema#82]
Hi, thank you for the library.

I think it would be useful to support the non-standard [ON CONFLICT Clause](https://www.sqlite.org/lang_conflict.html) in SQLite. Currently, the parser will throw unexpected token: "conflict" if it sees the clause.
I'd love to send a PR.

**Comment by duartealexf** [comment]
Hi @DukeManh

Currently this lib only supports MySQL / MariaDB. So there's no support for SQLite yet, and I barely have time to work on it :/
But feel free to create a PR to support SQLite :)

**Comment by DukeManh** [comment]
I see. Supporting SQLite would take quite some work :), for now, I just remove the clause completely and this lib still works nicely.
