### ISSUE TITLE
Getting different result running your provided script and DDL

### ISSUE THREAD

**Issue by aminechouicha** [duartealexf/sql-ddl-to-json-schema#91]
This is what I am getting below. Am I missing something?

[
  {
    name: 'users',
    columns: [ [Object], [Object], [Object], [Object], [Object] ],
    primaryKey: { columns: [Array] },
    uniqueKeys: [ [Object] ],
    options: { comment: 'All system users', engine: 'MyISAM' }
  }
]

**Comment by aminechouicha** [comment]
Never mind, I forgot to stringfy it. Thx

**Comment by duartealexf** [comment]
That looks correct. The console is truncating arrays and objects though, so to see the full object you might wanna `JSON.stringify` it.
