### ISSUE TITLE
Interestedin postgresql transformer

### ISSUE THREAD

**Issue by aminechouicha** [duartealexf/sql-ddl-to-json-schema#93]
Hi. 
I am interested to contribute for postgresql. Any pointer how to go about. Thank you.

**Comment by duartealexf** [comment]
Hi @aminechouicha thank you for taking interest! 💯 🥇 

Some first steps:

- Get familiarized to the [PostgreSQL syntax particularities](https://www.postgresql.org/docs/current/sql-syntax.html)
  - Get familiarized to (almost) everything supported by [PostgreSQL DDL](https://www.postgresql.org/docs/current/ddl.html)
- Get familiarized to [Nearley syntax](https://nearley.js.org)
- Refer to the [Contributing section](https://github.com/duartealexf/sql-ddl-to-json-schema#contributing) in the readme to understand where to put things together in the repository.

Most of the work is comprised of:

- Converting PostgreSQL syntax boards into Nearley language. For example, see this [synopsis](https://www.postgresql.org/docs/current/sql-altertable.html) section of the `ALTER TABLE` statement – you'll be writing a Nearley version of it... probably breaking it down into:
  - alter table definition
  - alter table: action (for the part where it says _"where action is one of"_ in the synopsis)
  - partition_bound_spec
  - column_constraint
  - table_constraint
  - table_constraint_using_index
  - ...etc

This project supports parsing most DDL statements for a given language, so if it parses `CREATE TABLE` then later `ALTER TABLE`, the output respects the table alterations made to the created table... so some post-parsing specific logic is required – for example, see what adding a primary key does to the table in MySQL: [here](https://github.com/duartealexf/sql-ddl-to-json-schema/blob/master/src/mysql/formatter/compact/models/rules/alter-table.ts#L223) and [here](https://github.com/duartealexf/sql-ddl-to-json-schema/blob/master/src/mysql/formatter/compact/models/table.ts#L864).

**Comment by duartealexf** [comment]
Let me know if there's anything else. Closing this for now.
